using Microsoft.AspNetCore.Identity;

namespace TaskAppApi.Models
{
    public class UserTask
    {
        public int Id { get; set; }  // Auto-generated by EF Core
        public string Title { get; set; }
        public string Description { get; set; }
        public DateTime DueDate { get; set; }
        public DateTime CreationDate { get; set; } = DateTime.Now;  // Automatically set when created
        public bool IsCompleted { get; set; } = false;  // Default is false
        public string Category { get; set; }
        public string UserId { get; set; }  // FK to the logged-in user
        public IdentityUser User { get; set; }  // Navigation property to User (optional)
    }
}
